# Generated by Django 3.1.6 on 2021-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0002_auto_20210221_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading_period',
            options={'ordering': ['month']},
        ),
        migrations.AlterField(
            model_name='reading_period',
            name='month',
            field=models.IntegerField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')]),
        ),
    ]
