# Generated by Django 3.1.6 on 2021-02-23 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterworks', '0005_auto_20210221_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replace_Water_Meter',
            new_name='Meter_Replace',
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='activity_logs',
            name='logs',
            field=models.CharField(choices=[('1', 'Information Changed'), ('2', 'Intalled Water Meter'), ('3', 'Change Info Water Meter'), ('4', 'Replace Water Meter')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='meter_installation',
            name='date_reading',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meter_installation',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Disconnected')], max_length=200),
        ),
        migrations.AlterField(
            model_name='reading',
            name='previous_reading_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_logs',
            name='user_logs',
            field=models.CharField(choices=[('1', 'Information Changed'), ('2', 'Intalled Water Meter'), ('3', 'Change Info Water Meter'), ('4', 'Replace Water Meter')], default=1, max_length=200),
        ),
    ]
