# Generated by Django 3.1.6 on 2021-02-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0008_auto_20210223_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter_replace',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterworks.profile'),
        ),
    ]
