# Generated by Django 3.1.6 on 2021-02-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0011_classification_rates_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='water_meter',
            field=models.IntegerField(default=0),
        ),
    ]
