# Generated by Django 3.1.6 on 2021-02-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0013_auto_20210225_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='application_name',
            new_name='name',
        ),
    ]
