# Generated by Django 3.1.6 on 2021-02-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0014_auto_20210226_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification_rates',
            old_name='rate',
            new_name='consumption',
        ),
        migrations.RemoveField(
            model_name='classification_rates',
            name='name',
        ),
        migrations.AddField(
            model_name='settings',
            name='disconnection_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='permanently_disconnected_charge',
            field=models.IntegerField(default=0),
        ),
    ]
