# Generated by Django 3.1.6 on 2021-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0015_auto_20210226_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification_rates',
            name='blocking_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='classification_rates',
            name='value_expression',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='disconnection_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='permanently_disconnected_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='water_meter_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
