# Generated by Django 3.1.6 on 2021-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0017_auto_20210227_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.FileField(default='', upload_to='logo/'),
            preserve_default=False,
        ),
    ]
