# Generated by Django 3.1.6 on 2021-03-01 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterworks', '0018_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_logs',
            name='logs',
            field=models.CharField(choices=[('1', 'Information Changed'), ('2', 'Intalled Water Meter'), ('3', 'Replace Water Meter'), ('4', 'Disconnected'), ('5', 'Disconnected Permanently')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='meter_installation',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Disconnected'), ('3', 'Permanently Disconnected')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_logs',
            name='user_logs',
            field=models.CharField(choices=[('1', 'Information Changed'), ('2', 'Intalled Water Meter'), ('3', 'Replace Water Meter'), ('4', 'Disconnected'), ('5', 'Disconnected Permanently')], default=1, max_length=200),
        ),
        migrations.CreateModel(
            name='Meter_Status_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Disconnected'), ('3', 'Permanently Disconnected')], max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waterworks.activity_logs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterworks.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
