# Generated by Django 3.1.6 on 2021-03-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterworks', '0019_auto_20210301_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='template/')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity_logs',
            name='logs',
            field=models.CharField(choices=[('1', 'Information Changed'), ('2', 'Intalled Water Meter'), ('3', 'Replace Water Meter'), ('4', 'Disconnected'), ('5', 'Condemn'), ('6', 'Active Meter')], default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_logs',
            name='user_logs',
            field=models.CharField(choices=[('1', 'Information Changed'), ('2', 'Intalled Water Meter'), ('3', 'Replace Water Meter'), ('4', 'Disconnected'), ('5', 'Condemn'), ('6', 'Active Meter')], default=1, max_length=200),
        ),
    ]
